mutation MutationNovel(
  $status: NovelStatus!
  $title: String!
  $synopsis: String!
  $gender: Gender!
  $genreId: Int!
  $tagIds: [Int!]!
  $novelId: Int
) {
  mutationNovel(
    status: $status
    title: $title
    synopsis: $synopsis
    gender: $gender
    genreId: $genreId
    tagIds: $tagIds
    novelId: $novelId
  ) {
    ...novel
  }
}

query MyNovels(
  $page: Int!
  $take: Int!
  $keyword: String!
  $gender: Gender
  $genreId: Int
  $tagIds: [Int!]
  $sortBy: String
  $sortOrder: SortOrder
) {
  myNovels(
    page: $page
    take: $take
    keyword: $keyword
    gender: $gender
    genreId: $genreId
    tagIds: $tagIds
    sortBy: $sortBy
    sortOrder: $sortOrder
  ) {
    total
    novels {
      ...novel
    }
    prev
    next
    totalPages
  }
}

mutation DeleteNovel($novelId: Int!) {
  deleteNovel(novelId: $novelId) {
    success
    message
  }
}
