import { Providers } from "@/components/providers";
import { Toaster } from "@workspace/ui/components/sonner";
import { TooltipProvider } from "@workspace/ui/components/tooltip";
import "@workspace/ui/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import * as React from "react";
import { ApolloWrapper } from "./apollo-wrapper";

export const inter = localFont({
  src: "../public/fonts/Inter.woff2",
  variable: "--font-inter",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`min-h-svh w-full antialiased`}>
        <ApolloWrapper>
          <Providers>
            <TooltipProvider>
              {children}
              <Toaster />
            </TooltipProvider>
          </Providers>
        </ApolloWrapper>
      </body>
    </html>
  );
}
