import * as React from "react";
import { Providers } from "@/components/providers";
import { inter } from "@/styles/fonts";
import "@workspace/ui/globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import type { Metadata } from "next";
import { ApolloWrapper } from "./apollo-wrapper";
import { ScrollToTopButton } from "@/components/scroll-to-top-button";
import { TooltipProvider } from "@workspace/ui/components/tooltip";
import { Toaster } from "@workspace/ui/components/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased font-semibold`}>
        <ApolloWrapper>
          <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID!}>
            <Providers>
              <TooltipProvider>
                {children}
                <div className="fixed inset-0 pointer-events-none -z-50">
                  <div className="absolute size-full bg-gradient-to-b from-gradient-from to-gradient-to"></div>
                  <div className="absolute w-full h-full bg-[url('/mask-image.svg')] bg-repeat"></div>
                </div>
                <ScrollToTopButton />
                <Toaster position="top-center" />
              </TooltipProvider>
            </Providers>
          </GoogleOAuthProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
