fragment book on Book {
  id
  name
  originalName
  synopsis
  poster
  kind
  gender
  status
  wordCnt
  flowerCnt
  readCnt
  reviewCnt
  chapterCnt
  commentCnt
  points
  createdAt
  newChapterAt
  author {
    id
    name
    originalName
  }
  createdBy {
    id
    nickname
    avatar
    avatarCover
  }
  tags {
    id
    name
    group {
      name
      color
    }
  }
  genre {
    id
    name
  }
}
