fragment user on User {
  id
  nickname
  email
  phone
  avatar
  coverImage
  role
  gender
  bio
  birthDate
  socialLinks
  keys
  tickets
  candies
  createdAt
  emailVerifiedAt
  isTwoFactorAuth
}
