mutation Register($nickname: String!, $email: String!, $password: String!) {
  register(nickname: $nickname, email: $email, password: $password) {
    success
    message
  }
}

mutation Login($email: String!, $password: String!, $code: String) {
  login(email: $email, password: $password, code: $code) {
    success
    message
    accessToken
    twoFactor
  }
}

mutation GoogleLogin($code: String!) {
  googleLogin(code: $code) {
    success
    message
    accessToken
    twoFactor
  }
}

mutation Logout {
  logout
}

mutation RefreshToken {
  refreshToken
}

mutation Verification($token: String!) {
  verification(token: $token) {
    success
    message
  }
}

mutation PasswordReset($email: String!) {
  passwordReset(email: $email) {
    success
    message
  }
}

mutation NewPassword($token: String!, $newPassword: String!) {
  newPassword(token: $token, newPassword: $newPassword) {
    success
    message
  }
}

mutation UpdateTwoFactor($isTwoFactorEnable: Boolean!, $code: String) {
  updateTwoFactor(isTwoFactorEnable: $isTwoFactorEnable, code: $code) {
    success
    message
    twoFactor
  }
}

mutation ResendTwoFactorCode($email: String!) {
  resendTwoFactorCode(email: $email) {
    success
    message
  }
}
