query BookOptions {
  kinds
  genders
  status
  genres {
    id
    name
  }
  tags {
    ...tag
  }
  tagGroups {
    id
    name
    color
  }
}

query Book($bookId: Int!) {
  book(bookId: $bookId) {
    ...book
  }
}

query HomePageData($month: Int!, $year: Int!) {
  editorPicks: paginatedBooks(page: 1, take: 6) {
    books {
      ...book
    }
  }
  recentUpdates: paginatedBooks(
    page: 1
    take: 10
    sortBy: "newChapterAt"
    sortOrder: desc
  ) {
    books {
      ...book
    }
  }
  mostReadBooks: paginatedRankingBooks(
    page: 1
    take: 10
    type: read
    month: $month
    year: $year
  ) {
    books {
      ...book
      readMonthly
    }
  }
  topNominations: paginatedRankingBooks(
    page: 1
    take: 10
    type: nominate
    month: $month
    year: $year
  ) {
    books {
      ...book
      nominateMonthly
    }
  }
}

query CreatedBooks(
  $page: Int!
  $take: Int!
  $keyword: String!
  $gender: Int
  $genreId: Int
  $tagIds: [Int!]
  $sortBy: String
  $sortOrder: SortOrder
) {
  createdBooks(
    page: $page
    take: $take
    keyword: $keyword
    gender: $gender
    genreId: $genreId
    tagIds: $tagIds
    sortBy: $sortBy
    sortOrder: $sortOrder
  ) {
    total
    books {
      ...book
    }
    prev
    next
    totalPages
  }
}
