import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import { inter } from "@/styles/fonts";
import "@/styles/globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import type { Metadata } from "next";
import { ApolloWrapper } from "./apollo-wrapper";
import { ScrollToTopButton } from "@/components/scroll-to-top-button";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} antialiased font-semibold`}>
        <ApolloWrapper>
          <GoogleOAuthProvider clientId={process.env.GOOGLE_CLIENT_ID!}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <TooltipProvider>
                {children}
                <ScrollToTopButton />
                <Toaster position="top-center"></Toaster>
              </TooltipProvider>
            </ThemeProvider>
          </GoogleOAuthProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
