query BookOptions {
  kinds
  genders
  status
  genres {
    id
    name
  }
  tags {
    id
    name
    group {
      name
      color
      bgColor
    }
  }
}

query Book($bookId: Int!) {
  book(bookId: $bookId) {
    ...book
  }
}
