query BookOptions {
  kinds
  genders
  status
  genres {
    id
    name
  }
  tags {
    id
    name
    group {
      name
      color
      bgColor
    }
  }
}

query Book($bookId: Int!) {
  book(bookId: $bookId) {
    ...book
  }
}

query HomePageData {
  paginatedBooks(page: 1, take: 10) {
    total
    books {
      ...book
    }
    prev
    next
    totalPages
  }
}
